### ISSUE TITLE
vmadm create for zones does not follow man page for dns_domain

### ISSUE THREAD

**Issue by jessegit** [joyent/smartos-live#277]
(Tested with multiarch 13.3.0)

From the man page:

```
     dns_domain:

         For OS VMs this specifies the domain value for /etc/hosts that gets set
         at create time. Updating this after create will have no effect.

         type: string (domain name)
         vmtype: OS
         listable: yes
         create: yes
         update: no
         default: local
```

Setting the dns_domain does not get set in /etc/hosts in any way. It is, however, added as 'search' domain in /etc/resolv.conf (which is not documented)

As I see it, the /etc/hosts part is broken and /etc/resolv.conf part should be documented.
