### ISSUE TITLE
'hostname' and 'dns_domain' are not honered in LX zones when defined in JSON provisioning payload

### ISSUE THREAD

**Issue by cmacrae** [joyent/smartos-live#514]
When provisioning an LX branded zone (from any of the available LX images on the official Joyent dataset repository), attempts to set `hostname` and `dns_domain` seem to fail.  

Here's an example payload:
``` yaml
{
    "brand": "lx",
    "image_uuid": "ffe82a0a-83d2-11e5-b5ac-f3e14f42f12d",
    "kernel_version": "3.19.0",
    "autoboot": true,
    "alias": "test",
    "zonename": "test",
    "hostname": "test.domain.tld",
    "dns_domain": "domain.tld",
    "resolvers": [
	"10.0.0.1"
    ],
    "max_physical_memory": 256,
    "max_swap": 256,
    "tmpfs": 256,
    "quota": 10,
    "nics": [
	{
	    "nic_tag": "admin",
	    "ip": "dhcp",
	    "mac": "32:71:31:b3:08:1g"
	}
    ]
}
```

The above payload provisions an Ubuntu 15.04 zone.  
When operating from this zone's shell, issuing `hostname` returns the intended `test`, but checking the FQDN with `hostname -f` simply returns `localhost`, when the expected output is `test.domain.tld`.

Furthermore; taking a look in `/etc/resolv.conf`, there is just a `nameserver` entry, but no `search`.  
I have tried numerous combinations of setting this statically in the JSON payload and defining the `admin` NIC's IP settings so as not to attempt retrieval of this information from a DHCP server. Or using the `option host-name "test.domain.tld";` in ISC DCHP and not setting it in the payload, or both, or a combination of all.  

Attempted updates to these particular values using `vmadm update` are also futile.  

Thanks in advance for any help on this, please do let me know if I can provide any more information.
